name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install and Build 🔧
        run: |
          cd frontentd-laba5
          npm ci
          npm run build
        env:
          CI: false

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: frontentd-laba5/build
          clean: true