# Generated by Django 4.2.4 on 2025-11-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('icon', models.CharField(default='fa-university', max_length=50, verbose_name='Иконка')),
                ('area', models.CharField(max_length=20, verbose_name='Площадь (кв.м)')),
                ('rooms', models.CharField(max_length=20, verbose_name='Количество помещений')),
                ('floor', models.CharField(max_length=10, verbose_name='Этаж')),
                ('total_floors', models.CharField(max_length=10, verbose_name='Всего этажей')),
                ('price', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
