# Generated by Django 4.2.4 on 2025-11-20 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('area', models.CharField(max_length=20, verbose_name='Площадь (кв.м)')),
                ('floor_count', models.IntegerField(default=1, verbose_name='Количество этажей')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'Строительный объект',
                'verbose_name_plural': 'Строительные объекты',
            },
        ),
        migrations.CreateModel(
            name='ConstructionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удален'), ('submitted', 'Сформирован'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('construction_type', models.CharField(default='Реконструкция', max_length=50, verbose_name='Тип строительства')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расчетная стоимость')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка на строительство',
                'verbose_name_plural': 'Заявки на строительство',
            },
        ),
        migrations.CreateModel(
            name='ConstructionRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('building_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_items', to='services_app.buildingobject', verbose_name='Строительный объект')),
                ('construction_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='construction_items', to='services_app.constructionrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Элемент заявки на строительство',
                'verbose_name_plural': 'Элементы заявок на строительство',
                'unique_together': {('construction_request', 'building_object')},
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
