# Generated by Django 5.2.8 on 2025-12-02 14:09

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services_app', '0002_buildingobject_constructionrequest_and_more'),
    ]

    operations = [
        # Создаем новую модель TechnicalSupervision
        migrations.CreateModel(
            name='TechnicalSupervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удален'), ('submitted', 'Сформирован'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('formed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('construction_type', models.CharField(default='Реконструкция', max_length=50, verbose_name='Тип строительства')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Расчетная стоимость')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_supervisions', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='moderated_supervisions', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
            ],
            options={
                'verbose_name': 'Заявка на технический надзор',
                'verbose_name_plural': 'Заявки на технический надзор',
            },
        ),
        
        # Создаем новую модель TechnicalSupervisionItem
        migrations.CreateModel(
            name='TechnicalSupervisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order_number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер')),
                ('building_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_items', to='services_app.buildingobject', verbose_name='Строительный объект')),
                ('technical_supervision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervision_items', to='services_app.technicalsupervision', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Элемент заявки на технический надзор',
                'verbose_name_plural': 'Элементы заявок на технический надзор',
                'unique_together': {('technical_supervision', 'building_object')},
            },
        ),
    ]