# Generated by Django 5.2.8 on 2025-12-02 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services_app', '0003_auto_20251202_1709'),
    ]

    operations = [
        # Удаляем старые модели
        migrations.DeleteModel(
            name='ConstructionRequestItem',
        ),
        migrations.DeleteModel(
            name='ConstructionRequest',
        ),
    ]